name: LIFEEC Mobile CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.3'
          channel: 'stable'
          cache: true
          
      - name: Install dependencies
        run: |
          flutter pub get
          flutter clean
          
      - name: Analyze project source
        run: flutter analyze
        
      - name: Build Android APK
        run: flutter build apk --debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: lifeec-mobile-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30
